services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v3.3.5
    restart: always
    command:
      - --accesslog=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - musical-spoon

  auth:
    container_name: auth
    image: auth
    restart: always
    build:
      context: apps/auth
    depends_on:
      auth_db:
        condition: service_started
    working_dir: /app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - musical-spoon
      - auth
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=Host(`auth.localhost`)
      - traefik.http.routers.auth.entryPoints=web
      - traefik.http.middlewares.forward-auth.forwardauth.address=http://auth/auth
      - traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-User-Role
      - traefik.docker.network=musical-spoon

  auth_db:
    image: mongo
    container_name: auth_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - auth_db:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - auth

  events:
    container_name: events
    image: events
    restart: always
    build:
      context: apps/events
    depends_on:
      auth:
        condition: service_started
      events_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    working_dir: /app
    environment:
      - EVENTS_POSTGRES_USER=${EVENTS_POSTGRES_USER}
      - EVENTS_POSTGRES_PASSWORD=${EVENTS_POSTGRES_PASSWORD}
      - EVENTS_POSTGRES_DB=${EVENTS_POSTGRES_DB}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - musical-spoon
      - events
    labels:
      - traefik.enable=true
      - traefik.http.routers.events.rule=Host(`events.localhost`)
      - traefik.http.routers.events.entryPoints=web
      - traefik.http.routers.events.middlewares=forward-auth
      - traefik.docker.network=musical-spoon

  events_db:
    image: postgres:latest
    container_name: events_db
    restart: always
    environment:
      - POSTGRES_USER=${EVENTS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${EVENTS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${EVENTS_POSTGRES_DB}
    volumes:
      - events_db:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - events

  orders:
    container_name: orders
    image: orders
    restart: always
    build:
      context: apps/orders
    depends_on:
      auth:
        condition: service_started
      orders_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    working_dir: /app
    environment:
      - ORDERS_POSTGRES_USER=${ORDERS_POSTGRES_USER}
      - ORDERS_POSTGRES_PASSWORD=${ORDERS_POSTGRES_PASSWORD}
      - ORDERS_POSTGRES_DB=${ORDERS_POSTGRES_DB}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - musical-spoon
      - orders
    labels:
      - traefik.enable=true
      - traefik.http.routers.orders.rule=Host(`orders.localhost`)
      - traefik.http.routers.orders.entryPoints=web
      - traefik.http.routers.orders.middlewares=forward-auth
      - traefik.docker.network=musical-spoon

  orders_db:
    image: postgres:latest
    container_name: orders_db
    restart: always
    environment:
      - POSTGRES_USER=${ORDERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDERS_POSTGRES_DB}
    volumes:
      - orders_db:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - orders

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - musical-spoon
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 15s
      start_interval: 3s
    

volumes:
  auth_db:
  events_db:
  orders_db:
  rabbitmq:

networks:
  musical-spoon:
    name: musical-spoon
    driver: bridge
  auth:
    name: auth
    driver: bridge
  events:
    name: events
    driver: bridge
  orders:
    name: orders
    driver: bridge
