services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v3.3
    restart: always
    command:
      - --config.file=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./core/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./core/traefik/dinamic-config.yml:/etc/traefik/dynamic-config.yml:ro"
    networks:
      - musical-spoon

  auth:
    container_name: auth
    image: auth
    restart: always
    build:
      context: apps/auth
    depends_on:
      auth_db:
        condition: service_started
    working_dir: /app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - auth
      - musical-spoon

  auth_db:
    image: mongo
    container_name: auth_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - auth_db:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - auth

volumes:
  auth_db:

networks:
  auth:
    name: auth
    driver: bridge
  musical-spoon:
    name: musical-spoon
    driver: bridge
