services:
  auth_db:
    image: mongo
    container_name: auth_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - auth_db:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  auth_db:
