import os

POSTGRES_DB = os.getenv('ORDERS_POSTGRES_DB', 'orders_db')
POSTGRES_HOST = os.getenv('ORDERS_POSTGRES_HOST', 'orders_db')
POSTGRES_PORT = os.getenv('ORDERS_POSTGRES_PORT', '5432')
POSTGRES_USER = os.environ['ORDERS_POSTGRES_USER']
POSTGRES_PASSWORD = os.environ['ORDERS_POSTGRES_PASSWORD']
POSTGRES_URL = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
