import os

POSTGRES_DB = os.getenv('EVENTS_POSTGRES_DB', 'events_db')
POSTGRES_HOST = os.getenv('EVENTS_POSTGRES_HOST', 'events_db')
POSTGRES_PORT = os.getenv('EVENTS_POSTGRES_PORT', '5432')
POSTGRES_USER = os.environ['EVENTS_POSTGRES_USER']
POSTGRES_PASSWORD = os.environ['EVENTS_POSTGRES_PASSWORD']
POSTGRES_URL = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'

RABBITMQ_USER = os.environ['RABBITMQ_DEFAULT_USER']
RABBITMQ_PASS = os.environ['RABBITMQ_DEFAULT_PASS']
RABBITMQ_HOST = os.getenv('RABBITMQ_DEFAULT_HOST', 'rabbitmq')
RABBITMQ_PORT = os.getenv('RABBITMQ_DEFAULT_PORT', '5672')
RABBITMQ_URL = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@{RABBITMQ_HOST}:{RABBITMQ_PORT}'
