import os

POSTGRES_DB = os.getenv('EVENTS_POSTGRES_DB', 'events_db')

POSTGRES_HOST = os.getenv('EVENTS_POSTGRES_HOST', 'events_db')
POSTGRES_PORT = os.getenv('EVENTS_POSTGRES_PORT', '5432')
POSTGRES_USER = os.environ['EVENTS_POSTGRES_USER']
POSTGRES_PASSWORD = os.environ['EVENTS_POSTGRES_PASSWORD']

POSTGRES_URL = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
