# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json

log:
  level: DEBUG

api:
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic-config.yml
    watch: true